import type { Metadata } from "next";
import "../globals.css";
import LandingNavbar from "@/components/landing-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <LandingNavbar />
      {children}
    </div>
  );
}
